# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "node src/server.js"