# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-22"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "npm start"